language: php

php:
  - 5.4

perl:
  - "5.14.2"

python:
  - "2.7"

before_script:
  - export TRAVIS=true
  - ./console run dependencies
  - ./console install php
  - ./console install perl
  - ./console install cpanm
  - ./console install mongo
  - ./console install phpunit
  - ./console install phpmongo
  - ./console install perl_modules
  - ./console install apache_modules
  - ./console init
  - cat /home/travis/builds/fabiocicerchia/fabiocicerchia.github.com/config/virtual_host | sed -r "s/\/var\/www\/fabiocicerchia\/current\//\/home\/travis\/builds\/fabiocicerchia\/fabiocicerchia.github.com\//" > /etc/apache2/site-enabled/site
  - /etc/init.d/apache2 restart
  - phpenv rehash

script: ./console -s test
