language: php

php:
  - 5.4

perl:
  - "5.14.2"

python:
  - "2.7"

before_script:
  - export TRAVIS_CI=1
  - ./console install php
  - ./console install perl
  - ./console install cpanm
  - ./console install mongo
  - ./console install phpunit
  - ./console install phpmongo
  - ./console install perl_modules
  - ./console install apache_modules
  - ./console init
  - phpenv rehash

script: ./console -s test